services:
  - type: web
    name: suomi-oppi
    runtime: python
    buildCommand: ""
    startCommand: python3 server.py
    envVars:
      - key: PORT
        value: 10000
      - key: PYTHON_VERSION
        value: 3.12.0
